name: "Validate/Test and Deploy Resources"

on:
    pull_request:
        branches:
            - main
            - dev


env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}


jobs:
    validation:
        name: "Validation Job"
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Python Setup
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            
            - name: Run Python Helper Script
              run: |
                cd script
                python3 replace_tf_values.py
          
            - name: Upload Updated Terraform Files
              uses: actions/upload-artifact@v3
              with:
                name: updated-terraform-files
                path: iac/

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
            
            - name: Validate Terraform
              run: |
                cd iac
                terraform init
                terraform validate

            - name: Plan Terraform Changes
              run: | 
                cd iac
                terraform plan -out=tfplan

            - name: Upload Plan Artifact
              uses: actions/upload-artifact@v3
              with:
                name: terraform-plan
                path: iac/tfplan

    lint_testing_frontend_files:
        name: "Test Website Files"
        needs: validation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: "16"

            - name: Install Testing Tools
              run: |
                npm install -g htmlhint stylelint eslint

            - name: Test HTML Files
              run: |
                htmlhlint index.html

            - name: Test HTML Files
              run: |
                htmlhlint error.html
            
            - name: Test CSS Files
              run: |
                stylelint style.css
            
            - name: Test JS Files
              run: |
                eslint script.js

    deployment:
        name: "Deploy Resources"
        runs-on: ubuntu-latest
        needs:
            - validation
            - lint_testing_frontend_files

        steps:
            
            - name: Checkout Code
              uses: actions/checkout@v2
            
            - name: Download Updated Terraform Files
              uses: actions/download-artifact@v3
              with:
                name: updated-terraform-files
                path: iac 

            - name: Download File Artifact
              uses: actions/download-artifact@v3
              with:
                name: terraform-plan
                path: iac

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Apply Terraform Resources
              run: |
                cd iac
                terraform init
                terraform apply -auto-approve tfplan